pandoc -s -o Exercice_Association_de_randonneurs.pdf Exercice_Association_de_randonneurs.md
pandoc -s -o Exercice_clés_primaires_et_étrangères.pdf Exercice_clés_primaires_et_étrangères.md
pandoc -s -o Exercice_Compagnie_aérienne.pdf Exercice_Compagnie_aérienne.md